config/routes.rb
Rails.application.routes.draw do
  

  OdinFacebook::Application.routes.draw do
  	resources :posts, only: [:create, :destroy] do
  		resources :likes, only: [:index, :create]
  		resources :comments, only: [:index, :create]
  	end
  end


  resources :likes, only: :destroy
  resources :comments, only: :destroy
  resources :friendships, only: [:create, :update, :destroy]

  devise_for :users

  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/notifications', to: 'static_pages#notifications'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friendships, dependent: :destroy
  has_many :received_friendships, foreign_key: "friend_id", class_name: "Friendship", 
                                                            dependent: :destroy

  has_many :active_friends, -> { where(friendships: { accepted: true }) }, 
  				 through: :friendships, source: :friend
  has_many :received_friends, -> { where(friendships: { accepted: true }) },
           through: :received_friendships, source: :user
  has_many :pending_friends, -> { where(friendships: { accepted: false }) }, 
           through: :friendships, source: :friend
  has_many :requested_friends, -> { where(friendships: { accepted: false }) }, 
           through: :received_friendships, source: :user

  has_many :posts, foreign_key: "author_id", dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :commented_posts, through: :comments, source: :post

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  # Call all friends
  def friends
  	active_friends | received_friends
  end

  # Call friends of pending requests
  def pending
  	pending_friends | requested_friends
  end

  # Get full name of user
  def full_name
  	"#{first_name} #{last_name}"
  end

  # Get friendship between two users
  def friendship_with(other_user)
    if active_friends.include?(other_user) or pending_friends.include?(other_user)
      friendships.find_by(friend_id: other_user.id)
    elsif received_friends.include?(other_user) or requested_friends.include?(other_user)
      received_friendships.find_by(user_id: other_user.id)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def show
  	@user = User.find(params[:id])
  	@post = current_user.posts.build if current_user == @user
  end

  def index
  	@users = User.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.full_name, class: "gravatar")
	end
end

app/views/users/_friend_options.html.erb
<% if current_user.pending_friends.include?(object) %>
	<p>Friend request pending.</p>
<% elsif !current_user.friends.include?(object) %>
	<%= link_to "Add Friend", friendships_path(friend_id: object), method: :post %>
<% else %>
	<%= "\u2713 Friends" %>
	<%= link_to "Unfriend", friendship_path(current_user.friendship_with(object)), method: :delete %>
<% end %>

app/views/users/_user.html.erb
<div class="gravatar"><%= link_to gravatar_for(user, size: 31), user %></div>
<div class="name"><%= link_to user.full_name, user %></div>

app/views/users/index.html.erb
<ul>
	<% @users.each do |user| %>
		<li>	
			<%= render user %>
			<%= render 'friend_options', object: user %>
		</li>
	<% end %>
</ul>

app/views/users/show.html.erb
<div class="user_header">
	<div class="gravatar"><%= link_to gravatar_for(@user), @user %></div>
	<div class="name"><%= link_to @user.full_name, @user %></div>
</div>

<%= render 'friend_options', object: @user if current_user != @user %>
<%= render 'shared/post_form' if current_user == @user %>

<h2>Friends <%= "(#{@user.friends.count})" %></h2>
	<ul>
		<% @user.friends.each do |friend| %>
			<li><%= render friend %></li>
		<% end %>
	</ul>

<%= render @user.posts %>