config/routes.rb
Rails.application.routes.draw do
  

  OdinFacebook::Application.routes.draw do
  	resources :posts, only: [:create, :destroy] do
  		resources :likes, only: [:index, :create]
  		resources :comments, only: [:index, :create]
  	end
  end


  resources :likes, only: :destroy
  resources :comments, only: :destroy
  resources :friendships, only: [:create, :update, :destroy]

  devise_for :users

  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/notifications', to: 'static_pages#notifications'

end

app/models/post.rb
class Post < ApplicationRecord
	validates :author_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
	
	belongs_to :author, class_name: "User"
	
	has_many :comments, dependent: :destroy
	has_many :commenters, through: :comments, source: :user

	has_many :likes, dependent: :destroy
	has_many :liking_users, through: :likes, source: :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to :back || root_url, notice: "Post created."
		else
			redirect_to :back, flash: { alert: @post.errors.full_messages.join(', ') }
		end
	end

	def show
	end

	def destroy
		Post.find(params[:id]).destroy
		redirect_to :back || root_url, notice: "Post deleted."
	end


	private

		def post_params
			params.require(:post).permit(:content)
		end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_for :comment, url: post_comments_path(object) do |f| %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<div class="field">
		<%= gravatar_for(current_user, size: 31) %>
		<%= f.text_area :content, placeholder: "Write a comment..." %>
	</div>
	<%= f.submit "Send", class: "button" %>
<% end %>

app/views/posts/_like_options.html.erb
<% if current_user.liked_posts.include?(object) %>
		<b>
			<%= link_to "\u2713 Like", object.likes.find_by(user_id: current_user.id), 
																										  method: :delete %>
		</b>																															  
<% else %>
	<%= link_to "Like", post_likes_path(object), method: :post %> 
<% end %>

app/views/posts/_post.html.erb
<div class="post">
	<div class="header">
		<%= render post.author %>
		<div class="timestamp">
			<%= time_ago_in_words(post.created_at) %>
			<% if current_user == post.author %>
				<%= link_to "Delete", post, method: :delete,
																		date: { confirm: "Are you sure?" } %>
			<% end %>
		</div>
	</div>
	<div class="content"><%= post.content %></div>
	<div class="like">
		<%= render 'posts/like_options', object: post %>
		<%= link_to pluralize(post.likes.count, "Like"), post_likes_path(post), class: "index" %>
	</div>
	<div class="comment">
		<%= render 'posts/comment_form', object: post %>
		<%= link_to pluralize(post.comments.count, "Comment"), post_comments_path(post) %>
	</div> 
</div>