config/routes.rb
Rails.application.routes.draw do
  

  OdinFacebook::Application.routes.draw do
  	resources :posts, only: [:create, :destroy] do
  		resources :likes, only: [:index, :create]
  		resources :comments, only: [:index, :create]
  	end
  end


  resources :likes, only: :destroy
  resources :comments, only: :destroy
  resources :friendships, only: [:create, :update, :destroy]

  devise_for :users

  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/notifications', to: 'static_pages#notifications'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user

	validates :user_id, presence: true
	validates :post_id, presence: true
	validates :content, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
	validates :user_id, presence: true
	validates :post_id, presence: true
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :author_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
	
	belongs_to :author, class_name: "User"
	
	has_many :comments, dependent: :destroy
	has_many :commenters, through: :comments, source: :user

	has_many :likes, dependent: :destroy
	has_many :liking_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friendships, dependent: :destroy
  has_many :received_friendships, foreign_key: "friend_id", class_name: "Friendship", 
                                                            dependent: :destroy

  has_many :active_friends, -> { where(friendships: { accepted: true }) }, 
  				 through: :friendships, source: :friend
  has_many :received_friends, -> { where(friendships: { accepted: true }) },
           through: :received_friendships, source: :user
  has_many :pending_friends, -> { where(friendships: { accepted: false }) }, 
           through: :friendships, source: :friend
  has_many :requested_friends, -> { where(friendships: { accepted: false }) }, 
           through: :received_friendships, source: :user

  has_many :posts, foreign_key: "author_id", dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :commented_posts, through: :comments, source: :post

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  # Call all friends
  def friends
  	active_friends | received_friends
  end

  # Call friends of pending requests
  def pending
  	pending_friends | requested_friends
  end

  # Get full name of user
  def full_name
  	"#{first_name} #{last_name}"
  end

  # Get friendship between two users
  def friendship_with(other_user)
    if active_friends.include?(other_user) or pending_friends.include?(other_user)
      friendships.find_by(friend_id: other_user.id)
    elsif received_friends.include?(other_user) or requested_friends.include?(other_user)
      received_friendships.find_by(user_id: other_user.id)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, except: :home
  before_filter :configure_permitted_parameters, if: :devise_controller?




    protected

    def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    	devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	after_action :save_previous_url, only: :index

	def index
		@comments = Comment.where(post_id: params[:post_id])
	end

	def create
		post = Post.find(params[:post_id])
		comment = post.comments.build(comments_params)
		if comment.save
			flash[:notice] = "Comment posted."
			redirect_to :back || root_url
		else
			redirect_to :back, flash: { alert: comment.errors.full_messages.join(', ') }
		end
	end

	def destroy
		Comment.find(params[:id]).destroy
		flash[:notice] = "Comment deleted."
		redirect_to :back || root_url
	end


	private

		def comments_params
			params.require(:comment).permit(:user_id, :content)
		end

		# Redirect to the page where the post was seen (either user's show page or home)
	  def save_previous_url
	    unless request.referer.include?('comments')
	      session[:previous_url] = URI(request.referer).path
	    end
	  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  
  def create
  	@friendship = current_user.friendships.build(friend_id: params[:friend_id])
	  if @friendship.save
	    redirect_to :back || root_url, notice: "Friend request sent."
	  else
	    redirect_to :back || root_url, notice: "Unable to send friend request."
	  end
  end

  def update
    @friendship = Friendship.find(params[:id])
    @friendship.accepted = true
    if @friendship.save
      redirect_to :back || root_url, notice: "Friend request confirmed."
    else
      redirect_to root_url, alert: "Could not confirm friend request."
    end
  end

  def destroy
	  @friendship = Friendship.find(params[:id])
    @friendship.destroy
    redirect_to :back || root_url, notice: "Removed friend."
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	after_filter "save_previous_url", only: :index

	def index
		@likes = Like.where(post_id: params[:post_id])
	end
	
	def create
		post = Post.find(params[:post_id])
		like = post.likes.build(user_id: current_user)
		like = current_user.likes.build(post_id: params[:post_id])
		if like.save
			redirect_to :back || root_url, notice: "Liked #{like.post.author.first_name}'s post."
		else
			redirect_to :back, alert: "Unable to like post."
		end
	end

	def destroy
		Like.find(params[:id]).destroy
		redirect_to :back, notice: "Unliked post."
	end

	private

	  # Redirect to the page where the post was seen (either user's show page or home)
    def save_previous_url
			unless request.referer.include?('likes')
				session[:previous_url] = URI(request.referrer).path
			end
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to :back || root_url, notice: "Post created."
		else
			redirect_to :back, flash: { alert: @post.errors.full_messages.join(', ') }
		end
	end

	def show
	end

	def destroy
		Post.find(params[:id]).destroy
		redirect_to :back || root_url, notice: "Post deleted."
	end


	private

		def post_params
			params.require(:post).permit(:content)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def show
  	@user = User.find(params[:id])
  	@post = current_user.posts.build if current_user == @user
  end

  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.full_name, class: "gravatar")
	end
end

app/views/layouts/_header.html.erb
<div class="navbar">
	<% if user_signed_in? %>  
    <%= link_to "Home", home_path %>
    <%= link_to "Notifications", notifications_path %>
    <%= link_to "Users", users_path %>
  	<%= link_to "Profile", user_path(current_user) %>
  	<%= link_to "Edit Account", edit_user_registration_path(current_user) %>
  	<div class="login">
      Signed in as <%= current_user.first_name %>. Not you?
    	<%= link_to "Log out", destroy_user_session_path, method: :delete %>
    </div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notifications/index.html.erb
<h1>Friend Requests</h1>
<% @requested_friends.each do |friend| %>
	<% friendship = current_user.friendship_with(friend) %>
	<%= link_to friend.full_name, friend %>
	<%= link_to "Confirm", friendship_path(friendship), method: "put" %>
	<%= link_to "Decline Request", friendship_path(friendship), method: :delete %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<div class="post_form">
	<%= form_for @post do |f| %>
		<%= f.text_area :content, placeholder: "What's on your mind, #{current_user.first_name}?" %>
		<br><%= f.submit "Post" %>
	<% end %>
</div>